// Package node is the npm/pnpm/yarn/bun runtime. Given a `runtime: node`
// service it auto-detects the package manager from a lockfile and synthesizes
// an install + run-script command pair, watching JS/TS source by default.
package node

import (
	"fmt"
	"path/filepath"

	"github.com/toaweme/blink/core/addon"
	"github.com/toaweme/blink/core/config"
)

// Runtime turns a `runtime: node` service into a `<pm> run <script>` command,
// optionally preceded by a guarded dependency install.
type Runtime struct{}

var _ addon.Runtime = Runtime{}

// Name returns the runtime identifier.
func (Runtime) Name() string { return "node" }

// Prepare synthesizes the run command (and a guarded install step) for a node
// service, defaulting the package manager from the service's lockfile and the
// script to "dev".
func (r Runtime) Prepare(cfg config.Config, svc config.Service) (addon.Plan, error) {
	nc := svc.Node
	if nc == nil {
		nc = &config.NodeConfig{}
	}

	pm := nc.PackageManager
	if pm == "" {
		pm = config.NodePackageManager(filepath.Join(cfg.DirRoot, svc.Dir))
	}

	script := nc.Script
	if script == "" {
		script = "dev"
	}

	install := true
	if nc.Install != nil {
		install = *nc.Install
	}

	commands := config.Commands{
		Run: &config.Command{
			Command: fmt.Sprintf("%s run %s", pm, script),
			Service: true,
		},
	}
	if install {
		// Setup runs once on boot and again only when a trigger file changes,
		// so dev reloads never reinstall. No node_modules guard needed.
		commands.Setup = []config.Command{{Command: installCommand(pm)}}
	}

	plan := addon.Plan{
		Defaults: config.Service{
			Fs: config.Fs{
				Extensions: []string{"js", "jsx", "ts", "tsx", "mjs", "cjs", "json", "css", "html"},
				// lockfiles are generated by install; watching them would cause a
				// spurious reload every time install rewrites one. package.json
				// (the setup trigger) is matched separately and is never excluded.
				Exclude: nodeLockfileExcludes,
			},
			Commands: commands,
		},
		SetupTriggers: nodeSetupTriggers,
	}
	return plan, nil
}

// nodeLockfileExcludes keeps every manager's lockfile out of the watch set, at
// any depth, so install's own writes never trigger a reload.
var nodeLockfileExcludes = []string{
	"**/package-lock.json",
	"**/pnpm-lock.yaml",
	"**/yarn.lock",
	"**/bun.lock",
	"**/bun.lockb",
}

// nodeSetupTriggers is the file whose change re-runs the install. Only
// package.json is listed, not lockfiles: lockfiles are install *outputs* (a
// bare `<pm> install` rewrites them), so triggering on them would loop install
// -> lockfile write -> install. package.json is the human-authored dependency
// source and bare installs never modify it. A lockfile-only change (e.g. a
// teammate bumping a transitive dep) is picked up on the next blink restart.
var nodeSetupTriggers = []string{"package.json"}

func installCommand(pm string) string {
	switch pm {
	case "yarn":
		return "yarn install"
	case "bun":
		return "bun install"
	default:
		// npm and pnpm both accept `install`.
		return pm + " install"
	}
}
