// Package node is the npm/pnpm/yarn/bun runtime. Given a `runtime: node`
// service it auto-detects the package manager from a lockfile and synthesizes
// an install + run-script command pair. A dev server that owns its own live
// reload (vite, next, nodemon, ...) is watched only for out-of-scope changes
// (package.json, node_modules) so blink never fights its HMR; a plain node
// server keeps the broad JS/TS source watch.
package node

import (
	"fmt"
	"path/filepath"

	"github.com/toaweme/blink/core/addon"
	"github.com/toaweme/blink/core/config"
)

// Runtime turns a `runtime: node` service into a `<pm> run <script>` command,
// optionally preceded by a guarded dependency install.
type Runtime struct{}

var _ addon.Runtime = Runtime{}

// Name returns the runtime identifier.
func (Runtime) Name() string { return "node" }

// Prepare synthesizes the run command (and a guarded install step) for a node
// service, defaulting the package manager from the service's lockfile and the
// script to "dev".
func (r Runtime) Prepare(cfg config.Config, svc config.Service) (addon.Plan, error) {
	nc := svc.Node
	if nc == nil {
		nc = &config.NodeConfig{}
	}

	pm := nc.PackageManager
	if pm == "" {
		pm = config.NodePackageManager(filepath.Join(cfg.DirRoot, svc.Dir))
	}

	script := nc.Script
	if script == "" {
		script = "dev"
	}

	install := true
	if nc.Install != nil {
		install = *nc.Install
	}

	commands := config.Commands{
		Run: &config.Command{
			Command: fmt.Sprintf("%s run %s", pm, script),
			Service: true,
		},
	}
	if install {
		// Setup runs once on boot and again only when a trigger file changes,
		// so dev reloads never reinstall. No node_modules guard needed.
		commands.Setup = []config.Command{{Command: installCommand(pm)}}
	}

	selfReloads := config.NodeDevScriptSelfReloads(filepath.Join(cfg.DirRoot, svc.Dir), script)
	plan := addon.Plan{
		Defaults: config.Service{
			Fs:       nodeWatchDefaults(selfReloads),
			Commands: commands,
		},
		SetupTriggers: nodeSetupTriggers,
	}
	return plan, nil
}

// nodeWatchDefaults picks the file-watch defaults for a node service. A dev
// server that owns its own live reload (vite, next, nodemon, ...) is watched
// only for package.json: strictInclude then skips source files entirely, so
// blink never restarts the process over an edit the dev server already handles
// in place; package.json still reloads and reinstalls via the setup trigger.
// A plain node server keeps the broad source watch so blink live-reloads it.
func nodeWatchDefaults(selfReloads bool) config.Fs {
	if selfReloads {
		return config.Fs{
			Include: []string{"package.json"},
			// package.json (the setup trigger) is matched by base name regardless
			// of Include, so it still reloads even under strictInclude; the lockfile
			// excludes keep install's own rewrites from leaking back in.
			Exclude: nodeLockfileExcludes,
		}
	}
	return config.Fs{
		Extensions: []string{"js", "jsx", "ts", "tsx", "mjs", "cjs", "json", "css", "html"},
		// lockfiles are generated by install; watching them would cause a
		// spurious reload every time install rewrites one. package.json
		// (the setup trigger) is matched separately and is never excluded.
		Exclude: nodeLockfileExcludes,
	}
}

// nodeLockfileExcludes keeps every manager's lockfile out of the watch set, at
// any depth, so install's own writes never trigger a reload.
var nodeLockfileExcludes = []string{
	"**/package-lock.json",
	"**/pnpm-lock.yaml",
	"**/yarn.lock",
	"**/bun.lock",
	"**/bun.lockb",
}

// nodeSetupTriggers is the file whose change re-runs the install. Only
// package.json is listed, not lockfiles: lockfiles are install *outputs* (a
// bare `<pm> install` rewrites them), so triggering on them would loop install
// -> lockfile write -> install. package.json is the human-authored dependency
// source and bare installs never modify it. A lockfile-only change (e.g. a
// teammate bumping a transitive dep) is picked up on the next blink restart.
var nodeSetupTriggers = []string{"package.json"}

func installCommand(pm string) string {
	switch pm {
	case "yarn":
		return "yarn install"
	case "bun":
		return "bun install"
	default:
		// npm and pnpm both accept `install`.
		return pm + " install"
	}
}
